### PR TITLE
SI-7160 Update specification of class Array (§12.3.4)

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Review by @odersky, please.

**Comment by soc** [comment]
@odersky The two issues you discovered should be fixed now.

**Comment by soc** [comment]
Ping?

**Comment by odersky** [comment]
Looks good now, thanks!

**Comment by adriaanm** [comment]
Cross-referencing https://github.com/iainmcgin/scala-ref-markdown/pull/19

**Pull request merged**
