### PR TITLE
add a Travis build

### PR DESCRIPTION
**Pull request by SethTisue**
and also upgrade to sbt 0.13.13 while we're at it

and Lightbend some Typesafes

### CODE REVIEW

**Comment by SethTisue** [comment]
all the resolving takes a reallllly long time on Travis

**Comment by SethTisue** [comment]
review by @adriaanm

**Comment by adriaanm** [comment]
LGTM -- nice!

**Comment by SethTisue** [comment]
I just noticed that I had already done the Typesafe->Lightbend changes on the 2.11.x branch and they just hadn't been merged to 2.12.x.

But 2.11.x has an sbt-native-packager downgrade we don't want (we hope!) on 2.12.x. So I think we can just consider the two branches to have diverged, now. We expect 2.11.9 to be the last 2.11.x release anyway; any real action will be on 2.12.x from now on.

**Comment by adriaanm** [comment]
SGTM

**Pull request merged**
