### PR TITLE
downgrade sbt-native-packager to 0.6.4

### PR DESCRIPTION
**Pull request by SethTisue**
this restores the 2.11.7 status quo for the 2.11.8 release.
see commit comments for further details

review by @adriaanm, cc @muuki88

### CODE REVIEW

**Comment by muuki88** [comment]
@SethTisue sorry for the inconvenience :(
If I have time, I'll we can fix some of the problems in native-packager.

**Comment by SethTisue** [comment]
> sorry for the inconvenience

np, none of the work is wasted if we can get it into 2.12 instead

**Comment by muuki88** [comment]
@SethTisue off-topic: do we have to change the vendor for sbt-native-packager as well?

**Comment by SethTisue** [comment]
> do we have to change the vendor for sbt-native-packager as well

@muuki88 is there a reason not to? I don't know what implications the vendor setting has, I just sort of assumed it was a string that might show up in UIs somewhere

**Comment by muuki88** [comment]
sorry, by vendor I meant the artifact groupid (`com.typesafe.sbt`)

**Comment by SethTisue** [comment]
well, in general, the thinking at Lightbend is that there's no big rush to make `com.typesafe` -> `com.lightbend` changes to group ids and such and the changes should be timed to coincide with big version bumps, so people will be needing to make changes anyway and won't mind one more

but sbt stuff specifically, I don't know, you'd have to ask the sbt folks

**Pull request merged**
