### PR TITLE
Scala mode fix

### PR DESCRIPTION
**Pull request by yuchangyuan**
Add some support for multi-line font lock.

### CODE REVIEW

**Comment by jsuereth** [comment]
@aemoncannon Any chance you can look at this?   I want to include it, but again I have no way to automatically verify fixes _and_ I'm clueless when it comes to emacs....

@yuchangyuan Question:  Any chance you could help me 'package' the emacs mode for the distribution?  If interested, ping me in email.

**Comment by freels** [comment]
This merge seems to have slowed things down a lot for me (in emacs 24.1). I tracked it down to commit 0a6a908640c56e204fe34795c38552389513bc2d .

**Comment by yuchangyuan** [comment]
I think set font-lock-multiline to t might be the cause of slow down. @freels, could you please set font-lock-multiline to nil in buffer and try again? And can you send me some sample files which make things slow?

**Comment by freels** [comment]
Here's a snippet of code that demonstrates the regression: https://gist.github.com/2949689.

Typing anywhere within the class body is unbearably slow. Smaller classes with fewer bodies don't suffer from the same problem. setting font-lock-multiline to nil has no effect. Interestingly enough, if most of the class body is outside the current visible window, then the slowdown isn't as bad.

Again, reverting commit 0a6a908 fixes the problem, so that narrows it down quite a bit.

**Comment by yuchangyuan** [comment]
I think I find the reason that slow down the emacs, it is actually related to variable font-lock-multiline. Set font-lock-multiline to nil (NOTE: should set the variable to nil, comment line 185 of scala-mode.el , kill the buffer and then reopen the file) will make emacs fast again. When font-lock-multiline is nil, emacs will only try to refontify a limited range(not cross current line) when insert a new character, but when this variable is t, emacs will try to refontify a large chunk of text every time when insert a new character.

  The cause of slow down is simple, but it's not easy to fix the problem with multiple line highlight function retained. I think I should find a better way to enable multiple line highlight instead of just set font-lock-multiline to t.

**Comment by yuchangyuan** [comment]
See  pull request #47 for a quick workaround.

**Pull request merged**
