### PR TITLE
SI-7629 Remove view bounds from spec

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by retronym** [comment]
These are still in the language, seems to soon to unspec them.

**Comment by soc** [comment]
The compiler is a superset of the things specified in the spec, I think it is perfectly fine if the compiler keeps supporting things which are deprecated, but I don't think we should burden the actual spec with deprecations.

**Comment by soc** [comment]
@retronym Anyway, given the usual speed at which spec PRs are handled, this commit will probably merged right in time with Scala 2.13.

**Comment by retronym** [comment]
@odersky doesn't read github pings; you should mail him directly if you want review.

**Comment by odersky** [comment]
I concur with Jason. There's no point to change the spec if the compiler still supports it. They will be removed, but the right way to do it is to change everything in sync.

**Comment by adriaanm** [comment]
Once the spec is in the main repo and follows the branching structure, we can update it there.

**Comment by adriaanm** [comment]
I've reopened and assigned to milestone 2.12

**Comment by adriaanm** [comment]
Please reopen on scala/scala when the time comes.

**Pull request closed without merging**
