### PR TITLE
Update sbt-native-packager to 1.3.3

### PR DESCRIPTION
**Pull request by raboof**
Refs #166

### CODE REVIEW

**Comment by adriaanm** [comment]
Let's give this a shot! /cc @SethTisue

**Comment by SethTisue** [comment]
yeah this makes me a little nervous but there's plenty of time to catch any regressions before 2.13 final. thanks @raboof

**Comment by SethTisue** [comment]
@muuki88 is there anything here we should be wary of...?

**Comment by SethTisue** [comment]
@raboof @muuki88 also are there any notable improvements that we should mention in the 2.13.0-M4 release notes?

**Comment by raboof** [comment]
@SethTisue I'm not aware of any specific ones - my motivation for this PR was mostly that I'd like to see https://github.com/sbt/sbt-native-packager/issues/477 happen for Scala, and being closer to the latest version will make that jump less scary when it does :)

**Comment by muuki88** [comment]
Sorry for the late response. From my perspective there are no relevant changes for this distribution.
If there should be any issues, don't hesitate to ping me 😄

**Pull request merged**
