### PR TITLE
fix errors in bug #135 and fix bug #66

### PR DESCRIPTION
**Pull request by bkanuka**
I chose scala-internals@googlegroups.com as the maintainer email address. Correct me if wrong.

### CODE REVIEW

**Comment by adriaanm** [comment]
Thank you, sorry this PR went unnoticed so long! I'm okay bumping our debian dependency to openjdk7, even though we don't technically require it. EDIT: Hmm, thinking about it, we should probably not change this mid-cycle. We're going to require 8 in 2.12 anyway, so let's defer the version bump until then.

**Comment by bkanuka** [comment]
`java-runtime-headless` is a kind of "catch-all" virtual package for Java in Debian. It basically means "you have java installed". In wheezy it is provided  by openjdk6 and openjdk7 (so as long as either is installed, the dependency is satisfied), in sid, openjdk8 will also satisfy the requirement of `java-runtime-headless`.  The benefit of using `java-runtime-headless` is that this dep can be satisfied by packages outside the default Debian repos. For example, if a user had a recent Oracle Java installed, they would still be able to install from this deb.

I know it looks this way, but my attempt was not to bump the version, but to follow packaging best-practices.

**Comment by adriaanm** [comment]
Oh right, sorry I didn't notice there was an OR between openjdk-7-jre-headless and java-runtime-headless

**Comment by adriaanm** [comment]
Thanks, @bkanuka!

**Comment by bkanuka** [comment]
Yup, okay you're totally right. But I think @adriaanm was implying in his first comment that I shouldn't bump _up_ to Java 7.  So I will change the depend to `java6-runtime-headless`

**Comment by adriaanm** [comment]
Sounds good, thanks! Users should be able to install current Scala on Java 6. Scala 2.12 will require Java 8.

**Pull request merged**
