### PR TITLE
SI-7161 Remove Manifests from spec

### PR DESCRIPTION
**Pull request by soc**
This is just the first half (removal of Manifests).
Let's hope someone with more in-depth knowledge of Tags will add
the second part (addition of Tags) in the future.

But anyway, no reason why we should let this rot any further.

### CODE REVIEW

**Comment by xeno-by** [comment]
This PR might be a bit premature, as scala-reflect isn't non-experimental yet.

**Comment by soc** [comment]
I think the compiler can be more liberal in what it accepts compared to the spec, but I think it is not necessary to keep more or less obsolete things on life-support in the spec (where "life-support" means "doctors have abandoned the hospital 5 years ago and threw away the keys").

Given the usual speed at which spec PRs are handled, this commit will probably merged right in time with Scala 2.13.

**Comment by odersky** [comment]
I think the status of manifests vs tags is still a bit unclear. I would prefer we leave it until TypeTags have become non-experiemental

**Comment by adriaanm** [comment]
assigned for milestone 2.12

**Comment by adriaanm** [comment]
Please reopen on scala/scala when the time comes.

**Comment by SethTisue** [comment]
@soc interested in picking this back up?

**Comment by soc** [comment]
@SethTisue I'm not sure whether I have already removed this in my fork of the spec.

**Comment by soc** [comment]
Just had a look, it's still there, but I think my change wouldn't be useful to you as it's not even in this repo anymore. I migrated all documentation into one repo back in 2015. (Wouldn't it make more sense to reword it in terms of `ClassTag`s anyway instead of removing it?

**Comment by SethTisue** [comment]
I wasn't expressing an opinion about what the best fix was, just hoping someone fixes it somehow.

As for the which-repo issue, even if you're not interesting in submitting a PR yourself in the correct repo, a link to your proposed changes, for someone else to use as a basis for a PR in our repo if they choose, would be of nonzero helpfulness.

**Comment by soc** [comment]
Sorry, if it was worded confusingly. I haven't removed it in my version, the rest was based on the hypothetical assumption that such a change existed.

**Pull request closed without merging**
