### PR TITLE
FIX #141 Upgrading to native-packager 1.0.4 and autoplugins

### LINKED ISSUE #141: Upgrade to latest sbt-native-packager
I tried to move from current 0.6.4 to both 0.7.x and 0.8.x, but it breaks debian packaging: https://github.com/scala/scala-dist/commit/2035c468ab8e0021551b5115a43fe0845de43797 (see parent commits for other attempts, which all fail in the same way.)

/cc @muuki88

### PR DESCRIPTION
**Pull request by muuki88**
Merry Christmas :christmas_tree: 

Seems like the `0644` chmod before the copy destroys the copy attempt of sbt.
However using the jdeb implementation works just fine (seem so).

### CODE REVIEW

**Comment by adriaanm** [comment]
Thanks again, @muuki88, and happy holidays! We'll use this to roll 2.11.6 and 2.12.0-M1. I unfortunately ran out of time for 2.11.5 -- our Jenkins caught fire, so I've been swamped with that.

**Comment by adriaanm** [comment]
Testing on our new release CI: http://scala-ci.typesafe.com/job/scala-release-2.11.x/8/console

**Comment by muuki88** [comment]
Ahh... windows needs some love as well

```
windows:packageBin from windows:packageBin (C:\jenkins\workspace\scala-release-2.11.x-windows\build.sbt:24
```

http://scala-ci.typesafe.com/job/scala-release-2.11.x-windows/5/console

**Comment by SethTisue** [comment]
@adriaanm does this need some attention?

**Comment by adriaanm** [comment]
It would be good to upgrade if/when possible.

**Comment by muuki88** [comment]
I can upgrade the versions ( unfortunately in two weeks ) if this helps.

**Comment by SethTisue** [comment]
@muuki88 ping! still interested?

**Comment by SethTisue** [comment]
@muuki88 does this result in any user-visible changes that we should mention in the release notes?

**Comment by muuki88** [comment]
Nothing I can think of. Startscript, permissions stay the same.

**Comment by SethTisue** [comment]
Thanks Muuki!

**Comment by SethTisue** [comment]
oh, I shouldn't have merged this, it breaks on Windows: https://scala-ci.typesafe.com/job/scala-2.11.x-release-package-windows/295/console . I should have inquired more closely about Muuki's earlier comment about it.

**Comment by muuki88** [comment]
I'll try to have a look this or next week. Have to setup a windows machine :D

**Comment by adriaanm** [comment]
In the mean time, could we revert to get the nightlies back to green?

**Comment by adriaanm** [comment]
Thanks for looking into this, @muuki88!

**Comment by SethTisue** [comment]
reverted in 07c427028a3f687f554da62f11a2444faf2d2c15

**Pull request merged**
