### PR TITLE
Gedit3 plugin for Scala

### PR DESCRIPTION
**Pull request by snim2**
Adds a Gedit3 plugin from the repo git@github.com:snim2/gedit-scala-plugin.git which adds automatic compilation and error highlighting and other features for Scala files in gedit3. The README has been updated to include instructions for both the syntax highlighter and the plugin. A BASH script to automatically install both parts of the gedit support has also been added.

### CODE REVIEW

**Comment by jsuereth** [comment]
any chance we can get this to merge cleanly again?

**Comment by nacho** [comment]
(as a gedit developer) I suggest language plugins to be managed as backends of gedit-code-assistance, see http://git.gnome.org/browse/gedit-code-assistance 

We already have backends for clang, python and xml.

**Comment by jsuereth** [comment]
@nacho That would make sense.   We don't have a true maintainer for it to contribute to gedit.   Would you be willing to accept what we have now?  I personally use Gedit a  lot, but I'm by no means a valid maintainer of the plugin.

**Comment by nacho** [comment]
well... I can't really put more time on maintaining plugins that I will not use to be honest.. If somebody wants to do the job and create a backend for gedit-code-assistance we (the gedit team) can try to help with it.

**Comment by jsuereth** [comment]
@snim2 Let me know if you're stil interested in this.  We'd love to have someone help maintain Scala gedit support, but I'm too overwhelemed myself to tackle it.

**Comment by snim2** [comment]
Hi @jsuereth yes, still interested. My students use Gedit + Scala so it would be good to have something stable to help them. Not long after I published the code and issued a pull request to you, some update of Gedit broke my plugin. Gah. So, porting to code-assistance may well be the answer to my problems too. 

If you want to close this pull request I'll issue a new one when there is something coherent for you to look at.

**Comment by jsuereth** [comment]
@snim2 Thanks much!  I very much appreciate any help you provide :)

**Pull request closed without merging**
