### PR TITLE
fix regression where we always ended up with Scala 2.10 JARs

### PR DESCRIPTION
**Pull request by SethTisue**
as a consequence of the sbt version bump in
https://github.com/scala/scala-dist/pull/165

fixes https://github.com/scala/scala-dist/issues/171

### CODE REVIEW

**Comment by SethTisue** [comment]
trying a dry run at https://scala-ci.typesafe.com/job/scala-2.12.x-release-package-unix/441/consoleFull

**Comment by SethTisue** [comment]
hmm. I'm going to go ahead and merge, and then start a 2.12.x-release-main run and we'll see what we get tomorrow.

we can check over the resulting distributions and if they look good, we're good, and if they don't, we can revert this and revert the sbt version bump so that the 2.12.1 release won't be delayed.

**Comment by SethTisue** [comment]
here's the new release-main run: https://scala-ci.typesafe.com/job/scala-2.12.x-release-main/610/consoleFull

**Comment by adriaanm** [comment]
Whew! 😓  good work!

**Pull request merged**
