### PR TITLE
Fix fontlock for parameters with default value.

### PR DESCRIPTION
**Pull request by yuchangyuan**
When any parameter binding in class or function definition has default value,
the following parameter bindings will not be correctly fontified. This commit
fix the problem.

For example:

def func(a: A,
         b: Int = 2,
         c: C,
         d: D)

Begin from the third line, the parameter bindings will not be correctly
fontified.

### CODE REVIEW

**Comment by ghost** [comment]
Hi,

HVesalai has been doing a number of indentation fixes, the last of which we are trying to get merged.  

With indentation issues out of the way, he already has a number of fontification fixes well underway on a branch of his scala-dist fork (see URL below).  

If it is OK we are going to pull your patch into there first and combine it into a suite of fontification patches into scala-dist.  Please feel free to communicate with HVesalai if you considering any other fontification related fixes.

https://github.com/hvesalai/scala-dist

Thanks for the patch !!!!

**Comment by yuchangyuan** [comment]
OK, I will communicate with HVesalai if I have any more fontification related fixes.

PS:  There are more than one branch about fontification in HVesalai's repository, are there any information about there branches? Or should I ask HVesalai directly?

**Comment by hvesalai** [comment]
Hi,

the https://github.com/hvesalai/scala-dist/tree/font-lock branch has the stable stuff that should be good.

I haven't yet tested it that much, but I've now rebased it to include the indent fixes.

yuchangyuan, if you have time, you are free to merge or "cherry pick" my changes to your pull request.

**Comment by hvesalai** [comment]
Hi, just want to add that I've been working on a complete rewrite of a scala-mode for emacs. It's called scala-mode2 and is here: https://github.com/hvesalai/scala-mode2

Because I'm now developing and maintaining scala-mode2, I will not have time (or much interest) in looking at the old scala-mode. I will propose including scala-mode2 in the scala-dist at some point when I fill it is mature enough.

Until then, I wish that none of these pull requests pend on my actions.

**Comment by yuchangyuan** [comment]
OK, I will cancel this pull request.

**Pull request closed without merging**
